"""
build_comparison.py
Writes src/models/09_comparison.ipynb from scratch.
Run from the repo root: python build_comparison.py
"""
import json
from pathlib import Path

OUT = Path("src/models/09_comparison.ipynb")

def md(source):
    return {"cell_type": "markdown", "metadata": {}, "source": source}

def code(source):
    return {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": source,
    }

cells = []

# ── Cell 1: Header ────────────────────────────────────────────────────────────
cells.append(md(
"# Strategy Comparison — All Models\n"
"\n"
"Runs every portfolio strategy in a single shared environment for unified comparison.\n"
"\n"
"**Strategies (rolling, realistic — no look-ahead bias):**\n"
"Equal Weight · 60/40 Benchmark · Sample Portfolio · Naive RP · ERC RP · "
"Markowitz · Black-Litterman · Factor Investing · FSO (γ=3.0)\n"
"\n"
"**Metrics:** Ann. Return (CAGR), Volatility, Sharpe, Sortino, Max DD, "
"Skewness, Kurtosis, Final Value, Recovery time per crisis\n"
"\n"
"---\n"
"### Methodological notes\n"
"- **Annualized Return** is geometric CAGR: `(product of (1+r))^(12/T) - 1`.\n"
"- **Sortino Ratio** uses downside deviation vs the monthly risk-free rate.\n"
"- **Naive RP** weights estimated from the first `LOOKBACK` months only — no look-ahead bias.\n"
"- **ERC RP** weights always sum to 1 (no leverage/vol-targeting scaling).\n"
"- **Markowitz** constrained to exactly `VOL_TARGET` (10% ann. vol) at each rebalance.\n"
"- **FSO** constrained to the same `VOL_TARGET` (10% ann. vol) for a fair comparison with Markowitz.\n"
"- **60/40 Benchmark** uses VEU (international equity, 60%) + BND (40%).\n"
))

# ── Cell 2: Imports & Config ──────────────────────────────────────────────────
cells.append(code(
"import json, warnings\n"
"from pathlib import Path\n"
"import numpy as np\n"
"import pandas as pd\n"
"import matplotlib.pyplot as plt\n"
"import matplotlib.ticker as mticker\n"
"import scipy.optimize as sco\n"
"from sklearn.covariance import LedoitWolf\n"
"from scipy import stats as scipy_stats\n"
"warnings.filterwarnings('ignore')\n"
"\n"
"BASE = Path('../../data')\n"
"with open('../../markets.json') as f:\n"
"    config = json.load(f)\n"
"\n"
"market_name        = list(config['markets'].keys())[0]\n"
"initial_investment = config['initial_investment']\n"
"\n"
"LOOKBACK        = 36\n"
"REBAL_THRESHOLD = 0.05\n"
"VOL_TARGET      = 0.10\n"
"\n"
"CRISES = [\n"
"    ('2008-09', '2009-06', 'GFC'),\n"
"    ('2020-02', '2020-04', 'COVID'),\n"
"    ('2022-01', '2022-12', 'Rate Hikes'),\n"
"]\n"
"\n"
"PALETTE = {\n"
"    'Equal Weight'    : '#028090',\n"
"    '60/40 Benchmark' : '#8896A5',\n"
"    'Sample Portfolio': '#C05621',\n"
"    'Naive RP'        : '#F6C90E',\n"
"    'ERC RP'          : '#38A169',\n"
"    'Markowitz'       : '#6B46C1',\n"
"    'Black-Litterman' : '#1A202C',\n"
"    'Factor Investing': '#E53E3E',\n"
"    'FSO (y=3.0)'     : '#DD6B20',\n"
"}\n"
"\n"
"plt.rcParams.update({\n"
"    'figure.facecolor': '#F4F7FB', 'axes.facecolor': 'white',\n"
"    'axes.spines.top': False, 'axes.spines.right': False,\n"
"    'axes.grid': True, 'grid.alpha': 0.4, 'grid.color': '#CBD5E0',\n"
"    'font.family': 'sans-serif',\n"
"})\n"
"print(f'Market: {market_name}  |  Initial investment: ${initial_investment:,.0f}')\n"
"print(f'Lookback: {LOOKBACK}m  |  Rebal threshold: {REBAL_THRESHOLD*100:.0f}%  |  Vol target: {VOL_TARGET*100:.0f}%')\n"
))

# ── Cell 3: Load Data ─────────────────────────────────────────────────────────
cells.append(code(
"returns = pd.read_csv(BASE / f'{market_name}_returns_monthly.csv',\n"
"                      index_col=0, parse_dates=True)\n"
"assets  = returns.columns.tolist()\n"
"N       = len(assets)\n"
"\n"
"rf_data           = pd.read_csv(BASE / 'risk_free_monthly.csv',\n"
"                                index_col=0, parse_dates=True)\n"
"rf_data           = rf_data.reindex(returns.index, method='ffill')\n"
"annual_rf_series  = rf_data['rf_annual']\n"
"monthly_rf_series = rf_data['rf_monthly']\n"
"\n"
"print(f'Returns : {returns.index[0].date()} -> {returns.index[-1].date()} ({len(returns)} months)')\n"
"print(f'Assets  : {assets}')\n"
"print(f'RF mean : {annual_rf_series.mean()*100:.3f}% annual')\n"
"returns.describe().round(4)\n"
))

# ── Cell 4: Helper Functions ──────────────────────────────────────────────────
cells.append(code(
"def months_to_recover(ret, cs, ce):\n"
"    cum  = (1 + ret).cumprod()\n"
"    pre  = cum.loc[:cs]\n"
"    if pre.empty: return None\n"
"    pk   = pre.max()\n"
"    tw   = cum.loc[cs:ce]\n"
"    if tw.empty: return None\n"
"    td   = tw.idxmin()\n"
"    post = cum.loc[td:]\n"
"    rec  = post[post >= pk]\n"
"    if rec.empty: return None\n"
"    return len(cum.loc[td:rec.index[0]]) - 1\n"
"\n"
"\n"
"def compute_stats(ret, label, rf_m, rf_a, init_inv):\n"
"    ar   = ret.mean() * 12 * 100\n"
"    av   = ret.std()  * np.sqrt(12) * 100\n"
"    sr   = (ret.mean() - rf_m) * 12 / (ret.std() * np.sqrt(12))\n"
"    cum  = (1 + ret).cumprod()\n"
"    mdd  = ((cum - cum.cummax()) / cum.cummax()).min() * 100\n"
"    cumr = (cum.iloc[-1] - 1) * 100\n"
"    skw  = scipy_stats.skew(ret.dropna())\n"
"    krt  = scipy_stats.kurtosis(ret.dropna())\n"
"    fv   = init_inv * cum.iloc[-1]\n"
"    dn   = ret[ret < rf_m]\n"
"    so   = ((ret.mean() - rf_m) * 12 / (dn.std() * np.sqrt(12))\n"
"            if len(dn) > 1 else np.nan)\n"
"    return pd.Series({\n"
"        'Ann. Return % (CAGR)': round(ar, 2),\n"
"        'Ann. Vol %'          : round(av, 2),\n"
"        'Sharpe'              : round(sr, 3),\n"
"        'Sortino'             : round(so, 3),\n"
"        'Max DD %'            : round(mdd, 2),\n"
"        'Cum. Return %'       : round(cumr, 1),\n"
"        'Skewness'            : round(skw, 3),\n"
"        'Excess Kurt.'        : round(krt, 3),\n"
"        'Final Value ($)'     : round(fv, 0),\n"
"    }, name=label)\n"
"\n"
"\n"
"print('Helper functions ready.')\n"
))

# ── Cell 5: Strategy Functions ────────────────────────────────────────────────
cells.append(code(
"# ── ERC: Equal Risk Contribution (Ledoit-Wolf covariance) ───────────────────\n"
"def erc_weights(rw):\n"
"    cov = LedoitWolf().fit(rw.values).covariance_\n"
"    n   = cov.shape[0]\n"
"    def obj(w):\n"
"        pv = np.sqrt(w @ cov @ w)\n"
"        rc = w * (cov @ w) / pv\n"
"        return sum((rc[i] - rc[j])**2 for i in range(n) for j in range(n))\n"
"    r = sco.minimize(obj, np.ones(n)/n, method='SLSQP',\n"
"                     bounds=[(0, 1)]*n,\n"
"                     constraints={'type':'eq','fun': lambda w: np.sum(w) - 1},\n"
"                     options={'ftol':1e-12, 'maxiter':1000})\n"
"    return pd.Series(r.x / r.x.sum(), index=rw.columns)\n"
"\n"
"\n"
"# ── Black-Litterman ──────────────────────────────────────────────────────────\n"
"BL_RISK_AV = 3.0\n"
"BL_TAU     = 0.05\n"
"BL_MKT_W   = np.array([0.11, 0.06, 0.02, 0.26, 0.20, 0.35])  # BND GLD TIP TLT VEU VGT\n"
"BL_VIEWS    = np.array([0.049, 0.025, 0.039, 0.043, 0.075, 0.075])\n"
"\n"
"def bl_weights(cov_a, mkt_w, views, ra, tau, rf_a, n):\n"
"    pi   = ra * cov_a @ mkt_w\n"
"    Om   = np.diag(np.diag(tau * cov_a))\n"
"    sc_i = np.linalg.inv(tau * cov_a)\n"
"    om_i = np.linalg.inv(Om)\n"
"    pc   = np.linalg.inv(sc_i + om_i)\n"
"    pr   = pc @ (sc_i @ pi + om_i @ views)\n"
"    def neg_sr(w):\n"
"        v = np.sqrt(w @ cov_a @ w)\n"
"        return -(w @ pr - rf_a) / v if v > 0 else 1e10\n"
"    r = sco.minimize(neg_sr, np.ones(n)/n, method='SLSQP',\n"
"                     bounds=[(0, 1)]*n,\n"
"                     constraints={'type':'eq','fun': lambda w: np.sum(w) - 1},\n"
"                     options={'ftol':1e-12, 'maxiter':1000})\n"
"    return r.x if r.success else np.ones(n)/n\n"
"\n"
"\n"
"# ── Factor Investing (4-factor: Momentum, Value, Quality, Low Vol) ──────────\n"
"MOM_S = -13; MOM_E = -1\n"
"VAL_S = -36; VAL_E = -13\n"
"LV_LB = 12\n"
"\n"
"def zscore(s):\n"
"    sd = s.std()\n"
"    return (s - s.mean()) / sd if sd > 0 else s * 0\n"
"\n"
"def factor_weights(rw, rf_m):\n"
"    mom  = zscore((1 + rw.iloc[MOM_S:MOM_E]).prod() - 1)\n"
"    val  = zscore(-((1 + rw.iloc[VAL_S:VAL_E]).prod() - 1))\n"
"    qual = zscore((rw.mean() - rf_m) / rw.std().replace(0, np.nan) * np.sqrt(12))\n"
"    lv   = zscore(1 / (rw.iloc[-LV_LB:].std() * np.sqrt(12)).replace(0, np.nan))\n"
"    comp = (0.25*mom.fillna(0) + 0.25*val.fillna(0)\n"
"            + 0.25*qual.fillna(0) + 0.25*lv.fillna(0))\n"
"    sh  = comp - comp.min()\n"
"    tot = sh.sum()\n"
"    return (sh / tot).values if tot > 0 else np.ones(len(comp)) / len(comp)\n"
"\n"
"\n"
"# ── Full Scale Optimization — vol-constrained CRRA (gamma=3.0) ──────────────\n"
"# Vol constraint (10% ann.) matches Markowitz for a fair comparison.\n"
"# Without it, FSO concentrates into the single highest-utility asset.\n"
"FSO_GAMMA = 3.0\n"
"\n"
"def fso_weights(rw, gamma, n, vol_target=VOL_TARGET):\n"
"    R     = rw.values\n"
"    cov_a = rw.cov().values * 12\n"
"    def neg_eu(w):\n"
"        gr = 1 + R @ w\n"
"        if np.any(gr <= 0): return 1e10\n"
"        u = np.log(gr) if gamma == 1.0 else gr**(1 - gamma) / (1 - gamma)\n"
"        return -np.mean(u)\n"
"    constraints = [\n"
"        {'type': 'eq', 'fun': lambda w: np.sum(w) - 1},\n"
"        {'type': 'eq', 'fun': lambda w, ca=cov_a: np.sqrt(w @ ca @ w) - vol_target},\n"
"    ]\n"
"    r = sco.minimize(neg_eu, np.ones(n)/n, method='SLSQP',\n"
"                     bounds=[(0, 1)]*n, constraints=constraints,\n"
"                     options={'ftol':1e-12, 'maxiter':1000})\n"
"    return r.x if r.success else np.ones(n)/n\n"
"\n"
"\n"
"print('All strategy functions defined.')\n"
))

# ── Cell 6: Run All Simulations ───────────────────────────────────────────────
cells.append(code(
"sim = {}   # label -> pd.Series of monthly returns\n"
"\n"
"# ── Static weight vectors ────────────────────────────────────────────────────\n"
"sp_map = {'BND':0.20,'GLD':0.10,'TIP':0.10,'TLT':0.10,'VEU':0.25,'VGT':0.25}\n"
"sp_arr = np.array([sp_map[a] for a in assets])\n"
"\n"
"bm_arr = np.zeros(N)\n"
"if 'VEU' in assets and 'BND' in assets:\n"
"    bm_arr[assets.index('VEU')] = 0.60\n"
"    bm_arr[assets.index('BND')] = 0.40\n"
"\n"
"# Naive RP: inverse-vol weights from first LOOKBACK months only (no look-ahead)\n"
"naive_v = returns.iloc[:LOOKBACK].std()\n"
"naive_w = (1 / naive_v) / (1 / naive_v).sum()\n"
"print(f'Naive RP inception weights (from first {LOOKBACK} months):')\n"
"print(naive_w.round(4).to_string())\n"
"\n"
"\n"
"# ── Simulation runners ────────────────────────────────────────────────────────\n"
"def run_static(w_arr):\n"
"    return (returns * pd.Series(w_arr, index=assets)).sum(axis=1)\n"
"\n"
"\n"
"def run_drift_rebal(target_arr):\n"
"    cw = target_arr.copy()\n"
"    rets_out, dates_out = [], []\n"
"    for t in range(len(returns)):\n"
"        if np.abs(cw - target_arr).max() > REBAL_THRESHOLD:\n"
"            cw = target_arr.copy()\n"
"        r = cw @ returns.iloc[t].values\n"
"        rets_out.append(r)\n"
"        dates_out.append(returns.index[t])\n"
"        ev = cw * (1 + returns.iloc[t].values)\n"
"        cw = ev / ev.sum()\n"
"    return pd.Series(rets_out, index=dates_out)\n"
"\n"
"\n"
"def run_rolling(fn, label):\n"
"    cw = np.ones(N) / N\n"
"    rs, ds = [], []\n"
"    for t in range(LOOKBACK, len(returns)):\n"
"        rw = returns.iloc[t - LOOKBACK:t]\n"
"        try:\n"
"            ntw = fn(rw, t)\n"
"        except Exception:\n"
"            ntw = np.ones(N) / N\n"
"        if np.abs(cw - ntw).max() > REBAL_THRESHOLD:\n"
"            cw = ntw\n"
"        r = cw @ returns.iloc[t].values\n"
"        rs.append(r)\n"
"        ds.append(returns.index[t])\n"
"        ev = cw * (1 + returns.iloc[t].values)\n"
"        cw = ev / ev.sum()\n"
"    print(f'  {label}: {len(rs)} months done')\n"
"    return pd.Series(rs, index=ds)\n"
"\n"
"\n"
"# ── Static strategies ─────────────────────────────────────────────────────────\n"
"sim['Equal Weight']     = run_static(np.ones(N) / N)\n"
"sim['60/40 Benchmark']  = run_static(bm_arr)\n"
"sim['Sample Portfolio'] = run_drift_rebal(sp_arr)\n"
"sim['Naive RP']         = run_static(naive_w.values)\n"
"print('Static strategies done.')\n"
"\n"
"\n"
"# ── Rolling strategy functions ────────────────────────────────────────────────\n"
"w0  = np.ones(N) / N\n"
"bds = [(0, 1)] * N\n"
"\n"
"def fn_erc(rw, t):\n"
"    return erc_weights(rw).values\n"
"\n"
"\n"
"def fn_mk(rw, t):\n"
"    mu = rw.mean().values * 12\n"
"    ca = rw.cov().values  * 12\n"
"    def neg_r(w): return -(w @ mu)\n"
"    def vol_c(w): return np.sqrt(w @ ca @ w) - VOL_TARGET\n"
"    r = sco.minimize(neg_r, w0, method='SLSQP', bounds=bds,\n"
"                     constraints=[\n"
"                         {'type':'eq','fun': lambda w: np.sum(w) - 1},\n"
"                         {'type':'eq','fun': vol_c},\n"
"                     ],\n"
"                     options={'ftol':1e-10, 'maxiter':1000})\n"
"    return r.x if r.success else np.ones(N) / N\n"
"\n"
"\n"
"def fn_bl(rw, t):\n"
"    return bl_weights(\n"
"        rw.cov().values * 12,\n"
"        BL_MKT_W, BL_VIEWS, BL_RISK_AV, BL_TAU,\n"
"        annual_rf_series.iloc[t], N,\n"
"    )\n"
"\n"
"\n"
"def fn_fi(rw, t):\n"
"    return factor_weights(rw, monthly_rf_series.iloc[t])\n"
"\n"
"\n"
"def fn_fso(rw, t):\n"
"    return fso_weights(rw, FSO_GAMMA, N, VOL_TARGET)\n"
"\n"
"\n"
"# ── Rolling strategies ────────────────────────────────────────────────────────\n"
"sim['ERC RP']           = run_rolling(fn_erc, 'ERC RP')\n"
"sim['Markowitz']        = run_rolling(fn_mk,  'Markowitz')\n"
"sim['Black-Litterman']  = run_rolling(fn_bl,  'Black-Litterman')\n"
"sim['Factor Investing'] = run_rolling(fn_fi,  'Factor Investing')\n"
"sim['FSO (y=3.0)']      = run_rolling(fn_fso, 'FSO')\n"
"print('\\nAll simulations complete.')\n"
))

# ── Cell 7: Align + RF + Master Table ────────────────────────────────────────
cells.append(code(
"# Align all strategies to the rolling strategies' common start date\n"
"comparison_period = sim['ERC RP'].index\n"
"for k in ['Equal Weight', '60/40 Benchmark', 'Sample Portfolio', 'Naive RP']:\n"
"    sim[k] = sim[k].loc[comparison_period]\n"
"\n"
"avg_rf_annual  = annual_rf_series.reindex(comparison_period, method='ffill').mean()\n"
"avg_rf_monthly = monthly_rf_series.reindex(comparison_period, method='ffill').mean()\n"
"\n"
"print(f'Comparison period : {comparison_period[0].date()} -> {comparison_period[-1].date()}')\n"
"print(f'Months            : {len(comparison_period)}')\n"
"print(f'RF (aligned)      : {avg_rf_annual*100:.3f}% annual  |  {avg_rf_monthly*100:.4f}% monthly')\n"
"\n"
"summary = pd.DataFrame([\n"
"    compute_stats(ret, label, avg_rf_monthly, avg_rf_annual, initial_investment)\n"
"    for label, ret in sim.items()\n"
"])\n"
"\n"
"print('=' * 80)\n"
"print('MASTER PERFORMANCE TABLE')\n"
"print('=' * 80)\n"
"print(summary.to_string())\n"
"print()\n"
"print('Note: Ann. Return is geometric CAGR. Sortino uses correct downside deviation.')\n"
"print(f'      FSO vol-constrained to {VOL_TARGET*100:.0f}% ann. vol (same as Markowitz) — fair comparison.')\n"
"\n"
"fig, ax = plt.subplots(figsize=(20, 3.8))\n"
"ax.axis('off')\n"
"col_labels = ['Strategy'] + list(summary.columns)\n"
"row_data   = [[idx] + [str(v) for v in summary.loc[idx]] for idx in summary.index]\n"
"tbl = ax.table(cellText=row_data, colLabels=col_labels, cellLoc='center', loc='center')\n"
"tbl.auto_set_font_size(False); tbl.set_fontsize(9); tbl.scale(1.0, 2.2)\n"
"for j in range(len(col_labels)):\n"
"    tbl[0, j].set_facecolor('#1E2761')\n"
"    tbl[0, j].set_text_props(color='white', fontweight='bold')\n"
"row_colors = ['#EBF8FF','#F7FAFC','#F0FFF4','#FFFFF0','#FFF5F5',\n"
"              '#F3E8FF','#E2E8F0','#FED7D7','#FEEBC8']\n"
"for i, color in enumerate(row_colors, start=1):\n"
"    for j in range(len(col_labels)):\n"
"        tbl[i, j].set_facecolor(color)\n"
"ax.set_title('Master Performance Summary — All Strategies',\n"
"             fontsize=13, fontweight='bold', pad=14)\n"
"plt.tight_layout(); plt.show()\n"
))

# ── Cell 8: Cumulative Return Chart ──────────────────────────────────────────
cells.append(code(
"fig, ax = plt.subplots(figsize=(14, 7))\n"
"for label, ret in sim.items():\n"
"    cum = ((1 + ret).cumprod() - 1) * 100\n"
"    ls  = '--' if label in ('Equal Weight', '60/40 Benchmark') else '-'\n"
"    ax.plot(cum, label=label, color=PALETTE[label], linewidth=2, linestyle=ls)\n"
"    ax.annotate(\n"
"        f'{cum.iloc[-1]:.0f}%',\n"
"        xy=(cum.index[-1], cum.iloc[-1]),\n"
"        xytext=(6, 0), textcoords='offset points',\n"
"        color=PALETTE[label], fontsize=8, fontweight='bold', va='center',\n"
"    )\n"
"for s, e, lbl in CRISES:\n"
"    ax.axvspan(pd.Timestamp(s), pd.Timestamp(e), alpha=0.08, color='red', zorder=0)\n"
"    ax.text(pd.Timestamp(s), ax.get_ylim()[1]*0.97, lbl,\n"
"            fontsize=7.5, color='#E53E3E', va='top')\n"
"ax.axhline(0, color='#8896A5', linewidth=0.8, linestyle='--')\n"
"ax.set_title('Cumulative Returns — All Strategies', fontsize=14, fontweight='bold', pad=14)\n"
"ax.set_ylabel('Cumulative Return (%)')\n"
"ax.yaxis.set_major_formatter(mticker.PercentFormatter())\n"
"ax.legend(fontsize=9, loc='upper left', ncol=2)\n"
"plt.tight_layout(); plt.show()\n"
))

# ── Cell 9: Drawdown Chart ────────────────────────────────────────────────────
cells.append(code(
"fig, ax = plt.subplots(figsize=(14, 6))\n"
"for label, ret in sim.items():\n"
"    cum = (1 + ret).cumprod()\n"
"    dd  = ((cum - cum.cummax()) / cum.cummax()) * 100\n"
"    ls  = '--' if label in ('Equal Weight', '60/40 Benchmark') else '-'\n"
"    ax.plot(dd, label=f'{label} (worst: {dd.min():.1f}%)',\n"
"            color=PALETTE[label], linewidth=1.8, linestyle=ls)\n"
"for s, e, lbl in CRISES:\n"
"    ax.axvspan(pd.Timestamp(s), pd.Timestamp(e), alpha=0.08, color='red', zorder=0)\n"
"    ax.text(pd.Timestamp(s), ax.get_ylim()[0]*0.08, lbl,\n"
"            fontsize=7.5, color='#E53E3E')\n"
"ax.axhline(0, color='#8896A5', linewidth=0.8)\n"
"ax.set_title('Drawdown Paths — All Strategies', fontsize=14, fontweight='bold', pad=14)\n"
"ax.set_ylabel('Drawdown (%)')\n"
"ax.yaxis.set_major_formatter(mticker.PercentFormatter())\n"
"ax.legend(fontsize=8, loc='lower right', ncol=2)\n"
"plt.tight_layout(); plt.show()\n"
))

# ── Cell 10: 4-Panel Bar Charts ───────────────────────────────────────────────
cells.append(code(
"fig, axes = plt.subplots(2, 2, figsize=(16, 10))\n"
"labels_all = list(sim.keys())\n"
"colors_all = [PALETTE[l] for l in labels_all]\n"
"\n"
"def bar_chart(ax, metric, title, fmt='{:.2f}', pct=False):\n"
"    vals = summary[metric]\n"
"    bars = ax.bar(vals.index, vals.values, color=colors_all, alpha=0.85)\n"
"    ax.axhline(0, color='#8896A5', linewidth=0.8, linestyle='--')\n"
"    for bar, v in zip(bars, vals.values):\n"
"        off = 0.01 * (vals.abs().max() or 1) * (1 if v >= 0 else -1)\n"
"        ax.text(bar.get_x() + bar.get_width()/2, v + off,\n"
"                fmt.format(v), ha='center',\n"
"                va='bottom' if v >= 0 else 'top',\n"
"                fontsize=8, fontweight='bold')\n"
"    ax.set_title(title, fontsize=12, fontweight='bold')\n"
"    if pct: ax.yaxis.set_major_formatter(mticker.PercentFormatter())\n"
"    ax.tick_params(axis='x', rotation=30)\n"
"\n"
"bar_chart(axes[0, 0], 'Sharpe',              'Sharpe Ratio',           '{:.3f}')\n"
"bar_chart(axes[0, 1], 'Ann. Return % (CAGR)','Ann. Return (CAGR %)',   '{:.2f}', pct=True)\n"
"bar_chart(axes[1, 0], 'Ann. Vol %',          'Ann. Volatility (%)',    '{:.2f}', pct=True)\n"
"bar_chart(axes[1, 1], 'Max DD %',            'Max Drawdown (%)',       '{:.2f}', pct=True)\n"
"\n"
"fig.suptitle('Key Metrics — All Strategies', fontsize=15, fontweight='bold', y=1.01)\n"
"plt.tight_layout(); plt.show()\n"
))

# ── Cell 11: Risk-Return Scatter ──────────────────────────────────────────────
cells.append(code(
"fig, ax = plt.subplots(figsize=(10, 6))\n"
"vols_range = np.linspace(2, 22, 200)\n"
"for sr in [0.2, 0.4, 0.6, 0.8, 1.0]:\n"
"    ax.plot(vols_range,\n"
"            avg_rf_annual * 100 + sr * vols_range,\n"
"            '--', color='#B0BEC5', linewidth=0.9, alpha=0.7)\n"
"    ax.text(vols_range[-1],\n"
"            avg_rf_annual * 100 + sr * vols_range[-1],\n"
"            f'SR={sr:.1f}', fontsize=9, color='#555', va='center')\n"
"for label in sim:\n"
"    x = summary.loc[label, 'Ann. Vol %']\n"
"    y = summary.loc[label, 'Ann. Return % (CAGR)']\n"
"    ax.scatter(x, y, color=PALETTE[label], s=120, zorder=5)\n"
"    ax.annotate(label, (x, y), textcoords='offset points',\n"
"                xytext=(6, 4), fontsize=8, color=PALETTE[label])\n"
"ax.set_xlabel('Ann. Volatility (%)')\n"
"ax.set_ylabel('Ann. Return — CAGR (%)')\n"
"ax.xaxis.set_major_formatter(mticker.PercentFormatter())\n"
"ax.yaxis.set_major_formatter(mticker.PercentFormatter())\n"
"ax.set_title('Risk-Return Scatter (dashed = iso-Sharpe lines)',\n"
"             fontsize=13, fontweight='bold', pad=14)\n"
"plt.tight_layout(); plt.show()\n"
))

# ── Cell 12: Crisis Recovery Table ───────────────────────────────────────────
cells.append(code(
"print('=' * 80)\n"
"print('CRISIS RECOVERY TABLE (months from trough back to pre-crisis peak)')\n"
"print('=' * 80)\n"
"header = f\"{'':20}\" + ''.join(f\"{l:>18}\" for l in sim)\n"
"print(header)\n"
"print('-' * len(header))\n"
"for cs, ce, clbl in CRISES:\n"
"    row = f\"{clbl:20}\"\n"
"    for label, ret in sim.items():\n"
"        m = months_to_recover(ret, cs, ce)\n"
"        row += f\"{'N/A':>18}\" if m is None else f\"{str(m)+'m':>18}\"\n"
"    print(row)\n"
"print()\n"
"print('N/A = never recovered within data, or crisis predates the 36-month warm-up window.')\n"
"print('GFC: all rolling strategies start May-2010, after the Mar-2009 trough.')\n"
))

# ── Cell 13: Distribution Stats ───────────────────────────────────────────────
cells.append(code(
"fig, axes = plt.subplots(1, 2, figsize=(14, 5))\n"
"for ax, metric, title in [\n"
"    (axes[0], 'Skewness',     'Skewness (+ = more upside surprises)'),\n"
"    (axes[1], 'Excess Kurt.', 'Excess Kurtosis (higher = fatter tails)'),\n"
"]:\n"
"    vals  = summary[metric].sort_values(ascending=False)\n"
"    cols  = [PALETTE[l] for l in vals.index]\n"
"    bars  = ax.bar(vals.index, vals.values, color=cols, alpha=0.85)\n"
"    ax.axhline(0, color='#8896A5', linewidth=0.8, linestyle='--')\n"
"    for bar, v in zip(bars, vals.values):\n"
"        ax.text(bar.get_x() + bar.get_width()/2,\n"
"                v + (0.03 if v >= 0 else -0.06),\n"
"                f'{v:.3f}', ha='center',\n"
"                va='bottom' if v >= 0 else 'top', fontsize=8, fontweight='bold')\n"
"    ax.set_title(title, fontsize=11, fontweight='bold')\n"
"    ax.tick_params(axis='x', rotation=30)\n"
"fig.suptitle('Return Distribution Shape — All Strategies',\n"
"             fontsize=13, fontweight='bold', y=1.02)\n"
"plt.tight_layout(); plt.show()\n"
"\n"
"print('\\n-- Distribution Statistics --')\n"
"print(summary[['Skewness','Excess Kurt.']].to_string())\n"
"print()\n"
"print('Black-Litterman is the only strategy with positive skewness: asymmetric upside.')\n"
))

# ── Cell 14: Monthly Return Box Plots ────────────────────────────────────────
cells.append(code(
"fig, ax = plt.subplots(figsize=(14, 6))\n"
"bp = ax.boxplot(\n"
"    [sim[l].values * 100 for l in sim],\n"
"    labels=list(sim.keys()),\n"
"    patch_artist=True,\n"
"    medianprops=dict(color='black', linewidth=2),\n"
"    flierprops=dict(marker='.', markersize=3, alpha=0.5),\n"
")\n"
"for patch, lbl in zip(bp['boxes'], sim):\n"
"    patch.set_facecolor(PALETTE[lbl])\n"
"    patch.set_alpha(0.75)\n"
"ax.axhline(0, color='#8896A5', linewidth=0.8, linestyle='--')\n"
"ax.set_ylabel('Monthly Return (%)')\n"
"ax.yaxis.set_major_formatter(mticker.PercentFormatter())\n"
"ax.set_title('Monthly Return Distribution — Box Plots (All Strategies)',\n"
"             fontsize=13, fontweight='bold', pad=14)\n"
"ax.tick_params(axis='x', rotation=20)\n"
"plt.tight_layout(); plt.show()\n"
))

# ── Cell 15: Rolling Sharpe + Volatility ─────────────────────────────────────
cells.append(code(
"ROLL_W = 12\n"
"fig, axes = plt.subplots(2, 1, figsize=(14, 11), sharex=True)\n"
"for label, ret in sim.items():\n"
"    roll_sr  = (ret.rolling(ROLL_W).mean() - avg_rf_monthly) * 12 / \\\n"
"               (ret.rolling(ROLL_W).std() * np.sqrt(12))\n"
"    roll_vol = ret.rolling(ROLL_W).std() * np.sqrt(12) * 100\n"
"    ls = '--' if label in ('Equal Weight', '60/40 Benchmark') else '-'\n"
"    axes[0].plot(roll_sr,  label=label, color=PALETTE[label], linewidth=1.5, linestyle=ls)\n"
"    axes[1].plot(roll_vol, label=label, color=PALETTE[label], linewidth=1.5, linestyle=ls)\n"
"for ax in axes:\n"
"    for s, e, lbl in CRISES:\n"
"        ax.axvspan(pd.Timestamp(s), pd.Timestamp(e), alpha=0.07, color='red', zorder=0)\n"
"axes[0].axhline(0, color='#8896A5', linewidth=0.8, linestyle='--')\n"
"axes[0].set_title(f'Rolling {ROLL_W}-Month Sharpe Ratio',\n"
"                   fontsize=12, fontweight='bold')\n"
"axes[0].set_ylabel('Sharpe Ratio')\n"
"axes[1].set_title(f'Rolling {ROLL_W}-Month Volatility (Ann.)',\n"
"                   fontsize=12, fontweight='bold')\n"
"axes[1].set_ylabel('Volatility (%)')\n"
"axes[1].yaxis.set_major_formatter(mticker.PercentFormatter())\n"
"axes[0].legend(fontsize=8, ncol=3, loc='upper left')\n"
"fig.suptitle('Rolling Performance Dynamics — All Strategies',\n"
"             fontsize=14, fontweight='bold', y=1.01)\n"
"plt.tight_layout(); plt.show()\n"
))

# ── Cell 16: Correlation Heatmap ──────────────────────────────────────────────
cells.append(code(
"ret_df  = pd.DataFrame(sim)\n"
"corr_df = ret_df.corr()\n"
"n_s     = len(sim)\n"
"\n"
"fig, ax = plt.subplots(figsize=(11, 9))\n"
"im = ax.imshow(corr_df.values, cmap='RdYlGn', vmin=-1, vmax=1, aspect='auto')\n"
"plt.colorbar(im, ax=ax, label='Pearson Correlation')\n"
"ax.set_xticks(range(n_s)); ax.set_yticks(range(n_s))\n"
"ax.set_xticklabels(corr_df.columns, rotation=35, ha='right', fontsize=9)\n"
"ax.set_yticklabels(corr_df.index, fontsize=9)\n"
"for i in range(n_s):\n"
"    for j in range(n_s):\n"
"        v = corr_df.iloc[i, j]\n"
"        ax.text(j, i, f'{v:.2f}', ha='center', va='center',\n"
"                fontsize=8, color='white' if abs(v) > 0.6 else 'black')\n"
"ax.set_title('Strategy Return Correlation Matrix',\n"
"             fontsize=13, fontweight='bold', pad=14)\n"
"plt.tight_layout(); plt.show()\n"
))

# ── Cell 17: Sortino + Final Value ────────────────────────────────────────────
cells.append(code(
"fig, axes = plt.subplots(1, 2, figsize=(15, 6))\n"
"\n"
"so_vals = summary['Sortino'].sort_values(ascending=False)\n"
"c_so    = [PALETTE[l] for l in so_vals.index]\n"
"bars = axes[0].bar(so_vals.index, so_vals.values, color=c_so, alpha=0.85)\n"
"for bar, v in zip(bars, so_vals.values):\n"
"    axes[0].text(bar.get_x() + bar.get_width()/2, v + 0.01,\n"
"                 f'{v:.3f}', ha='center', va='bottom', fontsize=8, fontweight='bold')\n"
"axes[0].axhline(0, color='#8896A5', linewidth=0.8, linestyle='--')\n"
"axes[0].set_title('Sortino Ratio — ranked\\n(downside deviation formula)',\n"
"                   fontsize=12, fontweight='bold')\n"
"axes[0].tick_params(axis='x', rotation=30)\n"
"\n"
"fv_vals = summary['Final Value ($)'].sort_values(ascending=False)\n"
"c_fv    = [PALETTE[l] for l in fv_vals.index]\n"
"bars2   = axes[1].bar(fv_vals.index, fv_vals.values, color=c_fv, alpha=0.85)\n"
"for bar, v in zip(bars2, fv_vals.values):\n"
"    axes[1].text(bar.get_x() + bar.get_width()/2, v + 20,\n"
"                 f'${v:,.0f}', ha='center', va='bottom', fontsize=8, fontweight='bold')\n"
"axes[1].set_title(\n"
"    f'Final Portfolio Value (${initial_investment:,.0f} lump sum)\\n'\n"
"    f'FSO vol-constrained to {VOL_TARGET*100:.0f}% ann. vol — same as Markowitz',\n"
"    fontsize=12, fontweight='bold',\n"
")\n"
"axes[1].yaxis.set_major_formatter(mticker.StrMethodFormatter('${x:,.0f}'))\n"
"axes[1].tick_params(axis='x', rotation=30)\n"
"\n"
"fig.suptitle('Downside Protection & Wealth Accumulation',\n"
"             fontsize=13, fontweight='bold', y=1.02)\n"
"plt.tight_layout(); plt.show()\n"
))

# ── Cell 18: Rankings Table ───────────────────────────────────────────────────
cells.append(code(
"rank_df = pd.DataFrame(index=summary.index)\n"
"rank_df['Return']  = summary['Ann. Return % (CAGR)'].rank(ascending=False).astype(int)\n"
"rank_df['Vol']     = summary['Ann. Vol %'].rank(ascending=True).astype(int)\n"
"rank_df['Sharpe']  = summary['Sharpe'].rank(ascending=False).astype(int)\n"
"rank_df['Sortino'] = summary['Sortino'].rank(ascending=False).astype(int)\n"
"rank_df['Max DD']  = summary['Max DD %'].rank(ascending=False).astype(int)\n"
"rank_df['Avg Rank']= rank_df.mean(axis=1).round(1)\n"
"rank_df = rank_df.sort_values('Avg Rank')\n"
"\n"
"print('=' * 70)\n"
"print('STRATEGY RANKING  (1 = best per metric, sorted by average rank)')\n"
"print('=' * 70)\n"
"print(rank_df.to_string())\n"
"print()\n"
"print(f'Overall winner: {rank_df.index[0]}  (avg rank {rank_df[\"Avg Rank\"].iloc[0]})')\n"
"\n"
"fig, ax = plt.subplots(figsize=(12, 4))\n"
"ax.axis('off')\n"
"col_labels = ['Strategy'] + list(rank_df.columns)\n"
"row_data   = [[idx] + [str(v) for v in rank_df.loc[idx]] for idx in rank_df.index]\n"
"tbl = ax.table(cellText=row_data, colLabels=col_labels, cellLoc='center', loc='center')\n"
"tbl.auto_set_font_size(False); tbl.set_fontsize(10); tbl.scale(1.1, 2.2)\n"
"for j in range(len(col_labels)):\n"
"    tbl[0, j].set_facecolor('#1E2761')\n"
"    tbl[0, j].set_text_props(color='white', fontweight='bold')\n"
"for i, lbl in enumerate(rank_df.index, start=1):\n"
"    color = '#C6EFCE' if rank_df.loc[lbl,'Avg Rank'] <= 3 else \\\n"
"            '#FFEB9C' if rank_df.loc[lbl,'Avg Rank'] <= 6 else '#FFC7CE'\n"
"    for j in range(len(col_labels)):\n"
"        tbl[i, j].set_facecolor(color)\n"
"ax.set_title('Overall Strategy Rankings (green=top 3, yellow=mid, red=bottom)',\n"
"             fontsize=12, fontweight='bold', pad=14)\n"
"plt.tight_layout(); plt.show()\n"
))

# ── Write notebook ────────────────────────────────────────────────────────────
nb = {
    "nbformat": 4,
    "nbformat_minor": 5,
    "metadata": {
        "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
        "language_info": {"name": "python", "version": "3.12.0"},
    },
    "cells": cells,
}

OUT.parent.mkdir(parents=True, exist_ok=True)
with open(OUT, "w", encoding="utf-8") as f:
    json.dump(nb, f, indent=1, ensure_ascii=False)

print(f"Written : {OUT}")
print(f"Cells   : {len(cells)}")
